# Generated by Django 6.0.3 on 2026-04-19 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_conversation_craftalong_forumthread_forumreply_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatternEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pattern', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='api.pattern')),
            ],
        ),
    ]
