# Generated by Django 6.0.3 on 2026-04-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_patternembedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Patron disponible à la vente'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='sold_count',
            field=models.IntegerField(default=0, help_text='Nombre de ventes'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='stock_quantity',
            field=models.IntegerField(default=0, help_text='Quantité disponible en stock'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='unlimited_stock',
            field=models.BooleanField(default=False, help_text='Stock illimité'),
        ),
    ]
