# Generated by Django 6.0.3 on 2026-04-21 20:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pattern_is_active_pattern_sold_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='needlehook',
            options={'ordering': ['type', 'size_mm']},
        ),
        migrations.AlterModelOptions(
            name='yarnbrand',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='yarnline',
            options={'ordering': ['brand__name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='yarnstash',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Yarn Stash'},
        ),
        migrations.AddField(
            model_name='needlehook',
            name='cable_length_cm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='needlehook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='needlehook',
            name='length_cm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='needlehook',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='needlehook',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='needlehook',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='needlehook',
            name='size_uk',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='needlehook',
            name='size_us',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='needlehook',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='yarnbrand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yarnbrand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brands/'),
        ),
        migrations.AddField(
            model_name='yarnline',
            name='care_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yarnline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='yarnline',
            name='gauge',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='yarnline',
            name='recommended_needle_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='yarnline',
            name='weight_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='yarnstash',
            name='color_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='yarnstash',
            name='dye_lot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='yarnstash',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='yarn_stash/'),
        ),
        migrations.AddField(
            model_name='yarnstash',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yarnstash',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yarnstash',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='yarnstash',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='yarnstash',
            name='store',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='yarnstash',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='yarnstash',
            name='yarn_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stash_items', to='api.yarnline'),
        ),
        migrations.AlterField(
            model_name='needlehook',
            name='material',
            field=models.CharField(blank=True, choices=[('bambou', 'Bambou'), ('metal', 'Métal'), ('plastique', 'Plastique'), ('bois', 'Bois'), ('acrylique', 'Acrylique'), ('aluminium', 'Aluminium'), ('acier', 'Acier')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='needlehook',
            name='size_mm',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='needlehook',
            name='type',
            field=models.CharField(choices=[('aiguille_droite', 'Aiguille droite'), ('aiguille_circulaire', 'Aiguille circulaire'), ('dpn', 'DPN (Double Pointed Needles)'), ('crochet', 'Crochet'), ('tunisien', 'Crochet Tunisien')], max_length=30),
        ),
        migrations.AlterField(
            model_name='yarnstash',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='yarnline',
            unique_together={('brand', 'name')},
        ),
    ]
