# Generated by Django 6.0.3 on 2026-04-21 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_needlehook_options_alter_yarnbrand_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('markers', 'Marqueurs de mailles'), ('scissors', 'Ciseaux'), ('tape', 'Mètre ruban'), ('bag', 'Sac à projet'), ('blocking', 'Matériel de blocage'), ('buttons', 'Boutons'), ('other', 'Autre')], max_length=20)),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('condition', models.CharField(choices=[('new', 'Neuf'), ('like_new', 'Comme neuf'), ('used', 'Utilisé')], default='new', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='listings/accessories/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='listings/accessories/')),
                ('description', models.TextField(blank=True, null=True)),
                ('shipping_available', models.BooleanField(default=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NeedleListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('aiguille_droite', 'Aiguille droite'), ('aiguille_circulaire', 'Aiguille circulaire'), ('dpn', 'DPN (Double Pointed Needles)'), ('crochet', 'Crochet'), ('tunisien', 'Crochet Tunisien')], max_length=30)),
                ('size_mm', models.DecimalField(decimal_places=2, max_digits=4)),
                ('material', models.CharField(blank=True, choices=[('bambou', 'Bambou'), ('metal', 'Métal'), ('plastique', 'Plastique'), ('bois', 'Bois'), ('acrylique', 'Acrylique'), ('aluminium', 'Aluminium'), ('acier', 'Acier')], max_length=20, null=True)),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
                ('length_cm', models.IntegerField(blank=True, null=True)),
                ('cable_length_cm', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('condition', models.CharField(choices=[('new', 'Neuf'), ('like_new', 'Comme neuf'), ('used', 'Utilisé')], default='used', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='listings/needles/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='listings/needles/')),
                ('description', models.TextField(blank=True, null=True)),
                ('shipping_available', models.BooleanField(default=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('needle_hook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='api.needlehook')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needle_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='YarnListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
                ('colorway', models.CharField(blank=True, max_length=200, null=True)),
                ('weight', models.CharField(blank=True, choices=[('lace', 'Lace'), ('sport', 'Sport'), ('dk', 'DK'), ('worsted', 'Worsted'), ('aran', 'Aran'), ('bulky', 'Bulky'), ('super_bulky', 'Super Bulky')], max_length=20, null=True)),
                ('grams', models.IntegerField(blank=True, null=True)),
                ('meterage', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('dye_lot', models.CharField(blank=True, max_length=100, null=True)),
                ('condition', models.CharField(choices=[('new', 'Neuf'), ('like_new', 'Comme neuf'), ('used', 'Utilisé')], default='new', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='listings/yarn/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='listings/yarn/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='listings/yarn/')),
                ('description', models.TextField(blank=True, null=True)),
                ('shipping_available', models.BooleanField(default=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('pickup_location', models.CharField(blank=True, max_length=300, null=True)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yarn_listings', to=settings.AUTH_USER_MODEL)),
                ('yarn_stash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='api.yarnstash')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accessory_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='api.accessorylisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_favorites', to=settings.AUTH_USER_MODEL)),
                ('needle_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='api.needlelisting')),
                ('yarn_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='api.yarnlisting')),
            ],
            options={
                'unique_together': {('user', 'accessory_listing'), ('user', 'needle_listing'), ('user', 'yarn_listing')},
            },
        ),
    ]
