# Generated by Django 6.0.3 on 2026-04-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_marketplacesale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='pdf',
            field=models.FileField(default=1, upload_to='patterns/pdf/'),
            preserve_default=False,
        ),
    ]
