# Generated by Django 6.0.3 on 2026-04-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_pattern_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pattern',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='sold_count',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='stock_quantity',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='unlimited_stock',
        ),
    ]
